# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dfhcc_classifier}
  s.version = "1.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Orenstein"]
  s.date = %q{2010-02-08}
  s.email = %q{benjamin_orenstein@dfci.harvard.edu}
  s.executables = ["bayes.rb", "summarize.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "bin/bayes.rb",
     "bin/summarize.rb",
     "dfhcc_classifier.gemspec",
     "install.rb",
     "lib/dfhcc_classifier.rb",
     "lib/dfhcc_classifier/bayes.rb",
     "lib/dfhcc_classifier/extensions/string.rb",
     "lib/dfhcc_classifier/extensions/word_hash.rb",
     "test/bayes/bayesian_test.rb",
     "test/extensions/word_hash_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://www.dfhcc.harvard.edu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple bayesian classifier}
  s.test_files = [
    "test/test_helper.rb",
     "test/bayes/bayesian_test.rb",
     "test/extensions/word_hash_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

